#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

export TOMCAT_HOME={{pkg.svc_var_path}}/tc
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{bind.database.first.sys.ip}} -DMONGODB_SERVICE_PORT={{bind.database.first.cfg.port}}"
cp {{pkg.path}}/*.war $TOMCAT_HOME/webapps

exec ${TOMCAT_HOME}/bin/catalina.sh run
